// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/WhisperTextProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Textsecure {

  /// <summary>Holder for reflection information generated from Proto/WhisperTextProtocol.proto</summary>
  public static partial class WhisperTextProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/WhisperTextProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WhisperTextProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Qcm90by9XaGlzcGVyVGV4dFByb3RvY29sLnByb3RvEgp0ZXh0c2VjdXJl",
            "ImQKDldoaXNwZXJNZXNzYWdlEhQKDGVwaGVtZXJhbEtleRgBIAEoDBIPCgdj",
            "b3VudGVyGAIgASgNEhcKD3ByZXZpb3VzQ291bnRlchgDIAEoDRISCgpjaXBo",
            "ZXJ0ZXh0GAQgASgMIo8BChRQcmVLZXlXaGlzcGVyTWVzc2FnZRIWCg5yZWdp",
            "c3RyYXRpb25JZBgFIAEoDRIQCghwcmVLZXlJZBgBIAEoDRIWCg5zaWduZWRQ",
            "cmVLZXlJZBgGIAEoDRIPCgdiYXNlS2V5GAIgASgMEhMKC2lkZW50aXR5S2V5",
            "GAMgASgMEg8KB21lc3NhZ2UYBCABKAwidgoSS2V5RXhjaGFuZ2VNZXNzYWdl",
            "EgoKAmlkGAEgASgNEg8KB2Jhc2VLZXkYAiABKAwSFAoMZXBoZW1lcmFsS2V5",
            "GAMgASgMEhMKC2lkZW50aXR5S2V5GAQgASgMEhgKEGJhc2VLZXlTaWduYXR1",
            "cmUYBSABKAxCNgolb3JnLndoaXNwZXJzeXN0ZW1zLmxpYnNpZ25hbC5wcm90",
            "b2NvbEINV2hpc3BlclByb3Rvcw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Textsecure.WhisperMessage), global::Textsecure.WhisperMessage.Parser, new[]{ "EphemeralKey", "Counter", "PreviousCounter", "Ciphertext" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Textsecure.PreKeyWhisperMessage), global::Textsecure.PreKeyWhisperMessage.Parser, new[]{ "RegistrationId", "PreKeyId", "SignedPreKeyId", "BaseKey", "IdentityKey", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Textsecure.KeyExchangeMessage), global::Textsecure.KeyExchangeMessage.Parser, new[]{ "Id", "BaseKey", "EphemeralKey", "IdentityKey", "BaseKeySignature" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WhisperMessage : pb::IMessage<WhisperMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WhisperMessage> _parser = new pb::MessageParser<WhisperMessage>(() => new WhisperMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WhisperMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Textsecure.WhisperTextProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhisperMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhisperMessage(WhisperMessage other) : this() {
      _hasBits0 = other._hasBits0;
      ephemeralKey_ = other.ephemeralKey_;
      counter_ = other.counter_;
      previousCounter_ = other.previousCounter_;
      ciphertext_ = other.ciphertext_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhisperMessage Clone() {
      return new WhisperMessage(this);
    }

    /// <summary>Field number for the "ephemeralKey" field.</summary>
    public const int EphemeralKeyFieldNumber = 1;
    private readonly static pb::ByteString EphemeralKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString ephemeralKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EphemeralKey {
      get { return ephemeralKey_ ?? EphemeralKeyDefaultValue; }
      set {
        ephemeralKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ephemeralKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEphemeralKey {
      get { return ephemeralKey_ != null; }
    }
    /// <summary>Clears the value of the "ephemeralKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEphemeralKey() {
      ephemeralKey_ = null;
    }

    /// <summary>Field number for the "counter" field.</summary>
    public const int CounterFieldNumber = 2;
    private readonly static uint CounterDefaultValue = 0;

    private uint counter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Counter {
      get { if ((_hasBits0 & 1) != 0) { return counter_; } else { return CounterDefaultValue; } }
      set {
        _hasBits0 |= 1;
        counter_ = value;
      }
    }
    /// <summary>Gets whether the "counter" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCounter {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "counter" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCounter() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "previousCounter" field.</summary>
    public const int PreviousCounterFieldNumber = 3;
    private readonly static uint PreviousCounterDefaultValue = 0;

    private uint previousCounter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PreviousCounter {
      get { if ((_hasBits0 & 2) != 0) { return previousCounter_; } else { return PreviousCounterDefaultValue; } }
      set {
        _hasBits0 |= 2;
        previousCounter_ = value;
      }
    }
    /// <summary>Gets whether the "previousCounter" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPreviousCounter {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "previousCounter" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPreviousCounter() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "ciphertext" field.</summary>
    public const int CiphertextFieldNumber = 4;
    private readonly static pb::ByteString CiphertextDefaultValue = pb::ByteString.Empty;

    private pb::ByteString ciphertext_;
    /// <summary>
    /// PushMessageContent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Ciphertext {
      get { return ciphertext_ ?? CiphertextDefaultValue; }
      set {
        ciphertext_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ciphertext" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCiphertext {
      get { return ciphertext_ != null; }
    }
    /// <summary>Clears the value of the "ciphertext" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCiphertext() {
      ciphertext_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WhisperMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WhisperMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EphemeralKey != other.EphemeralKey) return false;
      if (Counter != other.Counter) return false;
      if (PreviousCounter != other.PreviousCounter) return false;
      if (Ciphertext != other.Ciphertext) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEphemeralKey) hash ^= EphemeralKey.GetHashCode();
      if (HasCounter) hash ^= Counter.GetHashCode();
      if (HasPreviousCounter) hash ^= PreviousCounter.GetHashCode();
      if (HasCiphertext) hash ^= Ciphertext.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEphemeralKey) {
        output.WriteRawTag(10);
        output.WriteBytes(EphemeralKey);
      }
      if (HasCounter) {
        output.WriteRawTag(16);
        output.WriteUInt32(Counter);
      }
      if (HasPreviousCounter) {
        output.WriteRawTag(24);
        output.WriteUInt32(PreviousCounter);
      }
      if (HasCiphertext) {
        output.WriteRawTag(34);
        output.WriteBytes(Ciphertext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEphemeralKey) {
        output.WriteRawTag(10);
        output.WriteBytes(EphemeralKey);
      }
      if (HasCounter) {
        output.WriteRawTag(16);
        output.WriteUInt32(Counter);
      }
      if (HasPreviousCounter) {
        output.WriteRawTag(24);
        output.WriteUInt32(PreviousCounter);
      }
      if (HasCiphertext) {
        output.WriteRawTag(34);
        output.WriteBytes(Ciphertext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEphemeralKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EphemeralKey);
      }
      if (HasCounter) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Counter);
      }
      if (HasPreviousCounter) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PreviousCounter);
      }
      if (HasCiphertext) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Ciphertext);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WhisperMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasEphemeralKey) {
        EphemeralKey = other.EphemeralKey;
      }
      if (other.HasCounter) {
        Counter = other.Counter;
      }
      if (other.HasPreviousCounter) {
        PreviousCounter = other.PreviousCounter;
      }
      if (other.HasCiphertext) {
        Ciphertext = other.Ciphertext;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EphemeralKey = input.ReadBytes();
            break;
          }
          case 16: {
            Counter = input.ReadUInt32();
            break;
          }
          case 24: {
            PreviousCounter = input.ReadUInt32();
            break;
          }
          case 34: {
            Ciphertext = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EphemeralKey = input.ReadBytes();
            break;
          }
          case 16: {
            Counter = input.ReadUInt32();
            break;
          }
          case 24: {
            PreviousCounter = input.ReadUInt32();
            break;
          }
          case 34: {
            Ciphertext = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PreKeyWhisperMessage : pb::IMessage<PreKeyWhisperMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PreKeyWhisperMessage> _parser = new pb::MessageParser<PreKeyWhisperMessage>(() => new PreKeyWhisperMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PreKeyWhisperMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Textsecure.WhisperTextProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreKeyWhisperMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreKeyWhisperMessage(PreKeyWhisperMessage other) : this() {
      _hasBits0 = other._hasBits0;
      registrationId_ = other.registrationId_;
      preKeyId_ = other.preKeyId_;
      signedPreKeyId_ = other.signedPreKeyId_;
      baseKey_ = other.baseKey_;
      identityKey_ = other.identityKey_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PreKeyWhisperMessage Clone() {
      return new PreKeyWhisperMessage(this);
    }

    /// <summary>Field number for the "registrationId" field.</summary>
    public const int RegistrationIdFieldNumber = 5;
    private readonly static uint RegistrationIdDefaultValue = 0;

    private uint registrationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RegistrationId {
      get { if ((_hasBits0 & 2) != 0) { return registrationId_; } else { return RegistrationIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        registrationId_ = value;
      }
    }
    /// <summary>Gets whether the "registrationId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRegistrationId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "registrationId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRegistrationId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "preKeyId" field.</summary>
    public const int PreKeyIdFieldNumber = 1;
    private readonly static uint PreKeyIdDefaultValue = 0;

    private uint preKeyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PreKeyId {
      get { if ((_hasBits0 & 1) != 0) { return preKeyId_; } else { return PreKeyIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        preKeyId_ = value;
      }
    }
    /// <summary>Gets whether the "preKeyId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPreKeyId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "preKeyId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPreKeyId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "signedPreKeyId" field.</summary>
    public const int SignedPreKeyIdFieldNumber = 6;
    private readonly static uint SignedPreKeyIdDefaultValue = 0;

    private uint signedPreKeyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SignedPreKeyId {
      get { if ((_hasBits0 & 4) != 0) { return signedPreKeyId_; } else { return SignedPreKeyIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        signedPreKeyId_ = value;
      }
    }
    /// <summary>Gets whether the "signedPreKeyId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSignedPreKeyId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "signedPreKeyId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSignedPreKeyId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "baseKey" field.</summary>
    public const int BaseKeyFieldNumber = 2;
    private readonly static pb::ByteString BaseKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString baseKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BaseKey {
      get { return baseKey_ ?? BaseKeyDefaultValue; }
      set {
        baseKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "baseKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBaseKey {
      get { return baseKey_ != null; }
    }
    /// <summary>Clears the value of the "baseKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBaseKey() {
      baseKey_ = null;
    }

    /// <summary>Field number for the "identityKey" field.</summary>
    public const int IdentityKeyFieldNumber = 3;
    private readonly static pb::ByteString IdentityKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString identityKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString IdentityKey {
      get { return identityKey_ ?? IdentityKeyDefaultValue; }
      set {
        identityKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "identityKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdentityKey {
      get { return identityKey_ != null; }
    }
    /// <summary>Clears the value of the "identityKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdentityKey() {
      identityKey_ = null;
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private readonly static pb::ByteString MessageDefaultValue = pb::ByteString.Empty;

    private pb::ByteString message_;
    /// <summary>
    /// WhisperMessage
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Message {
      get { return message_ ?? MessageDefaultValue; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "message" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMessage {
      get { return message_ != null; }
    }
    /// <summary>Clears the value of the "message" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PreKeyWhisperMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PreKeyWhisperMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RegistrationId != other.RegistrationId) return false;
      if (PreKeyId != other.PreKeyId) return false;
      if (SignedPreKeyId != other.SignedPreKeyId) return false;
      if (BaseKey != other.BaseKey) return false;
      if (IdentityKey != other.IdentityKey) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRegistrationId) hash ^= RegistrationId.GetHashCode();
      if (HasPreKeyId) hash ^= PreKeyId.GetHashCode();
      if (HasSignedPreKeyId) hash ^= SignedPreKeyId.GetHashCode();
      if (HasBaseKey) hash ^= BaseKey.GetHashCode();
      if (HasIdentityKey) hash ^= IdentityKey.GetHashCode();
      if (HasMessage) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPreKeyId) {
        output.WriteRawTag(8);
        output.WriteUInt32(PreKeyId);
      }
      if (HasBaseKey) {
        output.WriteRawTag(18);
        output.WriteBytes(BaseKey);
      }
      if (HasIdentityKey) {
        output.WriteRawTag(26);
        output.WriteBytes(IdentityKey);
      }
      if (HasMessage) {
        output.WriteRawTag(34);
        output.WriteBytes(Message);
      }
      if (HasRegistrationId) {
        output.WriteRawTag(40);
        output.WriteUInt32(RegistrationId);
      }
      if (HasSignedPreKeyId) {
        output.WriteRawTag(48);
        output.WriteUInt32(SignedPreKeyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPreKeyId) {
        output.WriteRawTag(8);
        output.WriteUInt32(PreKeyId);
      }
      if (HasBaseKey) {
        output.WriteRawTag(18);
        output.WriteBytes(BaseKey);
      }
      if (HasIdentityKey) {
        output.WriteRawTag(26);
        output.WriteBytes(IdentityKey);
      }
      if (HasMessage) {
        output.WriteRawTag(34);
        output.WriteBytes(Message);
      }
      if (HasRegistrationId) {
        output.WriteRawTag(40);
        output.WriteUInt32(RegistrationId);
      }
      if (HasSignedPreKeyId) {
        output.WriteRawTag(48);
        output.WriteUInt32(SignedPreKeyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRegistrationId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RegistrationId);
      }
      if (HasPreKeyId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PreKeyId);
      }
      if (HasSignedPreKeyId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SignedPreKeyId);
      }
      if (HasBaseKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BaseKey);
      }
      if (HasIdentityKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(IdentityKey);
      }
      if (HasMessage) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PreKeyWhisperMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasRegistrationId) {
        RegistrationId = other.RegistrationId;
      }
      if (other.HasPreKeyId) {
        PreKeyId = other.PreKeyId;
      }
      if (other.HasSignedPreKeyId) {
        SignedPreKeyId = other.SignedPreKeyId;
      }
      if (other.HasBaseKey) {
        BaseKey = other.BaseKey;
      }
      if (other.HasIdentityKey) {
        IdentityKey = other.IdentityKey;
      }
      if (other.HasMessage) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PreKeyId = input.ReadUInt32();
            break;
          }
          case 18: {
            BaseKey = input.ReadBytes();
            break;
          }
          case 26: {
            IdentityKey = input.ReadBytes();
            break;
          }
          case 34: {
            Message = input.ReadBytes();
            break;
          }
          case 40: {
            RegistrationId = input.ReadUInt32();
            break;
          }
          case 48: {
            SignedPreKeyId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PreKeyId = input.ReadUInt32();
            break;
          }
          case 18: {
            BaseKey = input.ReadBytes();
            break;
          }
          case 26: {
            IdentityKey = input.ReadBytes();
            break;
          }
          case 34: {
            Message = input.ReadBytes();
            break;
          }
          case 40: {
            RegistrationId = input.ReadUInt32();
            break;
          }
          case 48: {
            SignedPreKeyId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KeyExchangeMessage : pb::IMessage<KeyExchangeMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KeyExchangeMessage> _parser = new pb::MessageParser<KeyExchangeMessage>(() => new KeyExchangeMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KeyExchangeMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Textsecure.WhisperTextProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyExchangeMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyExchangeMessage(KeyExchangeMessage other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      baseKey_ = other.baseKey_;
      ephemeralKey_ = other.ephemeralKey_;
      identityKey_ = other.identityKey_;
      baseKeySignature_ = other.baseKeySignature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KeyExchangeMessage Clone() {
      return new KeyExchangeMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static uint IdDefaultValue = 0;

    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "baseKey" field.</summary>
    public const int BaseKeyFieldNumber = 2;
    private readonly static pb::ByteString BaseKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString baseKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BaseKey {
      get { return baseKey_ ?? BaseKeyDefaultValue; }
      set {
        baseKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "baseKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBaseKey {
      get { return baseKey_ != null; }
    }
    /// <summary>Clears the value of the "baseKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBaseKey() {
      baseKey_ = null;
    }

    /// <summary>Field number for the "ephemeralKey" field.</summary>
    public const int EphemeralKeyFieldNumber = 3;
    private readonly static pb::ByteString EphemeralKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString ephemeralKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EphemeralKey {
      get { return ephemeralKey_ ?? EphemeralKeyDefaultValue; }
      set {
        ephemeralKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ephemeralKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEphemeralKey {
      get { return ephemeralKey_ != null; }
    }
    /// <summary>Clears the value of the "ephemeralKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEphemeralKey() {
      ephemeralKey_ = null;
    }

    /// <summary>Field number for the "identityKey" field.</summary>
    public const int IdentityKeyFieldNumber = 4;
    private readonly static pb::ByteString IdentityKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString identityKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString IdentityKey {
      get { return identityKey_ ?? IdentityKeyDefaultValue; }
      set {
        identityKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "identityKey" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdentityKey {
      get { return identityKey_ != null; }
    }
    /// <summary>Clears the value of the "identityKey" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdentityKey() {
      identityKey_ = null;
    }

    /// <summary>Field number for the "baseKeySignature" field.</summary>
    public const int BaseKeySignatureFieldNumber = 5;
    private readonly static pb::ByteString BaseKeySignatureDefaultValue = pb::ByteString.Empty;

    private pb::ByteString baseKeySignature_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BaseKeySignature {
      get { return baseKeySignature_ ?? BaseKeySignatureDefaultValue; }
      set {
        baseKeySignature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "baseKeySignature" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBaseKeySignature {
      get { return baseKeySignature_ != null; }
    }
    /// <summary>Clears the value of the "baseKeySignature" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBaseKeySignature() {
      baseKeySignature_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KeyExchangeMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KeyExchangeMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (BaseKey != other.BaseKey) return false;
      if (EphemeralKey != other.EphemeralKey) return false;
      if (IdentityKey != other.IdentityKey) return false;
      if (BaseKeySignature != other.BaseKeySignature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasBaseKey) hash ^= BaseKey.GetHashCode();
      if (HasEphemeralKey) hash ^= EphemeralKey.GetHashCode();
      if (HasIdentityKey) hash ^= IdentityKey.GetHashCode();
      if (HasBaseKeySignature) hash ^= BaseKeySignature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasBaseKey) {
        output.WriteRawTag(18);
        output.WriteBytes(BaseKey);
      }
      if (HasEphemeralKey) {
        output.WriteRawTag(26);
        output.WriteBytes(EphemeralKey);
      }
      if (HasIdentityKey) {
        output.WriteRawTag(34);
        output.WriteBytes(IdentityKey);
      }
      if (HasBaseKeySignature) {
        output.WriteRawTag(42);
        output.WriteBytes(BaseKeySignature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasBaseKey) {
        output.WriteRawTag(18);
        output.WriteBytes(BaseKey);
      }
      if (HasEphemeralKey) {
        output.WriteRawTag(26);
        output.WriteBytes(EphemeralKey);
      }
      if (HasIdentityKey) {
        output.WriteRawTag(34);
        output.WriteBytes(IdentityKey);
      }
      if (HasBaseKeySignature) {
        output.WriteRawTag(42);
        output.WriteBytes(BaseKeySignature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (HasBaseKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BaseKey);
      }
      if (HasEphemeralKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EphemeralKey);
      }
      if (HasIdentityKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(IdentityKey);
      }
      if (HasBaseKeySignature) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BaseKeySignature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KeyExchangeMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasBaseKey) {
        BaseKey = other.BaseKey;
      }
      if (other.HasEphemeralKey) {
        EphemeralKey = other.EphemeralKey;
      }
      if (other.HasIdentityKey) {
        IdentityKey = other.IdentityKey;
      }
      if (other.HasBaseKeySignature) {
        BaseKeySignature = other.BaseKeySignature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            BaseKey = input.ReadBytes();
            break;
          }
          case 26: {
            EphemeralKey = input.ReadBytes();
            break;
          }
          case 34: {
            IdentityKey = input.ReadBytes();
            break;
          }
          case 42: {
            BaseKeySignature = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            BaseKey = input.ReadBytes();
            break;
          }
          case 26: {
            EphemeralKey = input.ReadBytes();
            break;
          }
          case 34: {
            IdentityKey = input.ReadBytes();
            break;
          }
          case 42: {
            BaseKeySignature = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
